package com.skillpulse.personalization;
import com.skillpulse.auth.AppUser; import com.skillpulse.practice.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.*; import java.util.*;
@Service public class PlanProgressService {
 private final PersonalizedPlanRepository plans; private final PersonalizedPlanDayRepository days; private final PersonalizedPlanTaskRepository tasks; private final PracticeSubjectRepository subjects; private final PracticeTopicRepository topics;
 public PlanProgressService(PersonalizedPlanRepository p,PersonalizedPlanDayRepository d,PersonalizedPlanTaskRepository t,PracticeSubjectRepository s,PracticeTopicRepository pt){plans=p;days=d;tasks=t;subjects=s;topics=pt;}
 @Transactional public PersonalizedPlan save(AppUser user,String subject,PersonalizationDtos.PlanResponse response,double adherence){for(PersonalizedPlan old:plans.findByUserIdAndActiveTrue(user.getId())){old.setActive(false);plans.save(old);}PersonalizedPlan plan=new PersonalizedPlan();plan.setUser(user);plan.setSubjectName(subject);plan.setSummary(response.getSummary()==null?"Personalized learning plan":response.getSummary());plan.setPrimaryWeakness(response.getPrimaryWeakness());plan.setEngine(response.getEngine());plan.setAdherenceRate(adherence);PracticeTopic linked=bestTopic(subject,response.getPrimaryWeakness());LocalDate start=LocalDate.now();for(PersonalizationDtos.PlanDay source:response.getDays()){PersonalizedPlanDay day=new PersonalizedPlanDay();day.setPlan(plan);day.setDayNumber(source.getDay());day.setTargetDate(start.plusDays(Math.max(0,source.getDay()-1)));day.setFocus(source.getFocus());day.setObjective(source.getObjective());day.setPlannedMinutes(source.getMinutes());for(String activity:source.getActivities()){PersonalizedPlanTask task=new PersonalizedPlanTask();task.setPlanDay(day);task.setTopic(linked);task.setDescription(activity);task.setRequiredAttempts(1);day.getTasks().add(task);}plan.getDays().add(day);}return plans.save(plan);}
 public double adherence(Long userId){List<PersonalizedPlanDay> prior=days.findByPlanUserIdAndTargetDateLessThanEqual(userId,LocalDate.now().minusDays(1));if(prior.isEmpty())return .5;int complete=0;for(PersonalizedPlanDay day:prior)if(day.isCompleted())complete++;return complete*1.0/prior.size();}
 @Transactional public void recordAttempt(AppUser user,PracticeTopic topic){for(PersonalizedPlanDay day:days.findByPlanUserIdAndTargetDate(user.getId(),LocalDate.now())){if(day.isCompleted()||!day.getPlan().isActive())continue;for(PersonalizedPlanTask task:tasks.findByPlanDayId(day.getId())){if(task.isCompleted())continue;if(task.getTopic()!=null&&!task.getTopic().getId().equals(topic.getId())&&!task.getTopic().getSubject().getId().equals(topic.getSubject().getId()))continue;task.setCompletedAttempts(task.getCompletedAttempts()+1);if(task.getCompletedAttempts()>=task.getRequiredAttempts()){task.setCompleted(true);task.setCompletedAt(Instant.now());}tasks.save(task);break;}refreshDay(day);}}
 @Transactional public void completeTask(AppUser user,Long taskId){PersonalizedPlanTask task=tasks.findById(taskId).orElseThrow(()->new IllegalArgumentException("Plan task not found."));if(!task.getPlanDay().getPlan().getUser().getId().equals(user.getId()))throw new IllegalArgumentException("Plan task not found.");task.setCompletedAttempts(task.getRequiredAttempts());task.setCompleted(true);task.setCompletedAt(Instant.now());tasks.save(task);refreshDay(task.getPlanDay());}
 @Transactional(readOnly=true) public Map<String,Object> current(Long userId){Map<String,Object> result=new LinkedHashMap<String,Object>();PersonalizedPlan plan=plans.findFirstByUserIdOrderByCreatedAtDesc(userId).orElse(null);if(plan==null){result.put("plan",null);return result;}result.put("planId",plan.getId());result.put("subject",plan.getSubjectName());result.put("adherenceRate",plan.getAdherenceRate());result.put("summary",plan.getSummary());result.put("primaryWeakness",plan.getPrimaryWeakness());result.put("engine",plan.getEngine());result.put("createdAt",plan.getCreatedAt().toString());result.put("today",LocalDate.now().toString());List<Map<String,Object>> dayRows=new ArrayList<Map<String,Object>>();for(PersonalizedPlanDay day:plan.getDays()){Map<String,Object> row=new LinkedHashMap<String,Object>();row.put("dayId",day.getId());row.put("day",day.getDayNumber());row.put("targetDate",day.getTargetDate().toString());row.put("focus",day.getFocus());row.put("objective",day.getObjective());row.put("minutes",day.getPlannedMinutes());row.put("completed",day.isCompleted());List<Map<String,Object>> taskRows=new ArrayList<Map<String,Object>>();for(PersonalizedPlanTask task:day.getTasks()){Map<String,Object> tr=new LinkedHashMap<String,Object>();tr.put("taskId",task.getId());tr.put("description",task.getDescription());tr.put("completed",task.isCompleted());tr.put("completedAttempts",task.getCompletedAttempts());tr.put("requiredAttempts",task.getRequiredAttempts());taskRows.add(tr);}row.put("tasks",taskRows);dayRows.add(row);}result.put("days",dayRows);return result;}
 @Transactional public void uncompleteTask(AppUser user,Long taskId){PersonalizedPlanTask task=tasks.findById(taskId).orElseThrow(()->new IllegalArgumentException("Plan task not found."));if(!task.getPlanDay().getPlan().getUser().getId().equals(user.getId()))throw new IllegalArgumentException("Plan task not found.");task.setCompletedAttempts(0);task.setCompleted(false);task.setCompletedAt(null);tasks.save(task);PersonalizedPlanDay day=task.getPlanDay();if(day.isCompleted()){day.setCompleted(false);day.setCompletedAt(null);days.save(day);}}
 /** Moves every unfinished day onto consecutive dates starting today (or tomorrow). Finished days keep their dates. */
 @Transactional public Map<String,Object> reschedule(AppUser user,boolean startTomorrow){PersonalizedPlan plan=plans.findFirstByUserIdOrderByCreatedAtDesc(user.getId()).orElseThrow(()->new IllegalArgumentException("You do not have a plan yet."));List<PersonalizedPlanDay> ordered=new ArrayList<PersonalizedPlanDay>(plan.getDays());Collections.sort(ordered,new Comparator<PersonalizedPlanDay>(){public int compare(PersonalizedPlanDay a,PersonalizedPlanDay b){return Integer.compare(a.getDayNumber(),b.getDayNumber());}});LocalDate date=LocalDate.now().plusDays(startTomorrow?1:0);int moved=0;for(PersonalizedPlanDay day:ordered){if(day.isCompleted())continue;day.setTargetDate(date);date=date.plusDays(1);days.save(day);moved++;}if(moved==0)throw new IllegalArgumentException("Every day of this plan is already done.");return current(user.getId());}
 private void refreshDay(PersonalizedPlanDay day){boolean all=!day.getTasks().isEmpty();for(PersonalizedPlanTask task:tasks.findByPlanDayId(day.getId()))if(!task.isCompleted()){all=false;break;}if(all&&!day.isCompleted()){day.setCompleted(true);day.setCompletedAt(Instant.now());days.save(day);}}
 private PracticeTopic bestTopic(String subject,String focus){for(PracticeSubject s:subjects.findAllByOrderByDisplayOrderAsc())if(s.getName().equalsIgnoreCase(subject)){List<PracticeTopic> list=topics.findBySubjectIdOrderByDisplayOrderAsc(s.getId());for(PracticeTopic t:list)if(focus!=null&&focus.toLowerCase().contains(t.getName().toLowerCase()))return t;return list.isEmpty()?null:list.get(0);}return null;}
}
